[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "TradeGate"
authors = [{ name = "RustinSoraki", email = "rustin.soraki@gmail.com" }]
dynamic = ["version", "description"]

[tool.flit.module]
name = "TradeGate"